name: ci
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pipx install poetry
      - name: Install deps
        run: poetry install --no-interaction --no-ansi
      - name: Lint (ruff)
        run: poetry run ruff check .
      - name: Format check (black)
        run: poetry run black --check .
      - name: Type check (mypy)
        run: poetry run mypy .
      - name: Tests
        run: poetry run pytest
